Improve UX
MILA-Wien/collectivo-ux pull request #101
Opened 2023-07-12 16:01 UTC by JoelForamitti

- Move extensions and dashboard into settings section & tags into users section
- Button to create new users
- Better layout for displaying data in ObjectDetail

![image](https://github.com/MILA-Wien/collectivo-ux/assets/57440945/9a302461-60d1-43b2-9226-3b2a3cecb72c)

2023-07-12 19:33 UTC, nanu-c requested changes

2023-07-12 19:33 UTC, nanu-c commented on src/components/core/CoreSettings.vue
> +                Version: {{ slotProps.data.version }}
That should be translated

2023-07-12 19:33 UTC, nanu-c commented on src/components/datatable/ObjectDetail.vue
> +                  {{ field.choices![value] }}
can we translate it?

2023-07-12 19:33 UTC, nanu-c commented on src/components/datatable/ObjectDetail.vue
> +                {{ data.detail[name] }}
same with this?

2023-07-12 19:33 UTC, nanu-c commented on src/components/datatable/ObjectDetail.vue
> +// }
This is commented code ;), pelase remove

2023-07-13 07:03 UTC, JoelForamitti commented on src/components/datatable/ObjectDetail.vue
> +// }
done!

2023-07-13 07:07 UTC, JoelForamitti commented on src/components/core/CoreSettings.vue
> +                Version: {{ slotProps.data.version }}
done!

2023-07-13 07:08 UTC, JoelForamitti commented on src/components/datatable/ObjectDetail.vue
> +                  {{ field.choices![value] }}
hmm i think we first need to write a safe wrapper for the translate function, as the application breaks if it receives anything else than a string. have added this to the board

2023-07-13 07:08 UTC, JoelForamitti commented on src/components/datatable/ObjectDetail.vue
> +                {{ data.detail[name] }}
same as above

2023-07-13 11:38 UTC, nanu-c approved these changes

2023-07-13 12:11 UTC, merged