Emails
MILA-Wien/collectivo-ux pull request #40
Opened 2023-01-12 16:36 UTC by JoelForamitti

This PR creates a frontend interface for the members emails API

- [x] API and Store for emails
- [ ] Datatables
- [ ] Details & Create
- [ ] HTML Form for templates (@nanu-c)

2023-01-18 13:03 UTC, JoelForamitti commented on src/components/extensions/members/MembersTable.vue
> +async function sendEmails() {
This function is still a todo

2023-01-18 13:04 UTC, JoelForamitti commented on src/components/datatable/ObjectDetail.vue
> +            <div v-else-if="field.input_type === 'html'">
This part ist still a TODO

2023-01-19 13:16 UTC, nanu-c requested changes

2023-01-19 13:16 UTC, nanu-c commented on src/App.vue
> -.p-datatable.p-datatable-gridlines .p-datatable-tbody > tr > td, .p-datatable.p-datatable-gridlines .p-datatable-thead > tr > th{
This should be in the `ObjectTable.vue` and not here

2023-01-19 14:21 UTC, JoelForamitti commented on src/App.vue
> -.p-datatable.p-datatable-gridlines .p-datatable-tbody > tr > td, .p-datatable.p-datatable-gridlines .p-datatable-thead > tr > th{
Done

2023-01-19 14:36 UTC, nanu-c approved these changes

2023-01-20 09:39 UTC, merged