register as user_not_member (natural person)
MILA-Wien/collectivo-ux pull request #49
Opened 2023-01-30 15:44 UTC by r-wasserman

This is a first PR attempt, covering: 
1. registration as natural person via `user_not_member`, in which only compulsory fields are filled (except checkbox indicated)
2. test data cleanup (see `beforeEach()`) 
3. Missing TODOs are indicated on top of `06_register_member.cy.ts`

2023-01-30 17:37 UTC, JoelForamitti requested changes
The new test didn't pass in the CI:

```  
1) register user_not_member, compulsory fields only (except checkboxes on page 4/5)
       register as natural person:
     CypressError: Timed out retrying after 4000ms: `cy.clear()` failed because this element:

`<input class="p-inputtext p-component" data-v-6c7919b5="">`

is being covered by another element:

`<div class="p-datepicker-header">...</div>`
```

Not sure what the mistake is, but maybe the videos that you can find here under artifact might be of help: https://github.com/MILA-Wien/collectivo-ux/actions/runs/4045446770

2023-01-31 13:14 UTC, nanu-c commented on src/assets/registrationForm.json
> +                    "id": "next-page-button",
Hey r, the id has to be unique. So you can change it to `next-page-button` but the next button has to be `next-page-button-1`

2023-02-01 16:45 UTC, r-wasserman commented on src/assets/registrationForm.json
> +                    "id": "next-page-button",
Hallo @nanu-c, that's a very good point. I took care of it and gave to `<button/>`s a unique id according to the formular page they're on.

2023-02-02 09:40 UTC, nanu-c commented on src/assets/registrationForm.json
> +                    "id": "next-page-button",
perfect!

2023-02-14 11:08 UTC, JoelForamitti approved these changes

2023-02-14 11:09 UTC, merged