Dynamic multiple choice fields
MILA-Wien/collectivo-ux pull request #52
Opened 2023-02-07 11:25 UTC by nanu-c

The formviewer now allows to fetch fields from the backend or use the options defined in the json

```
                {
                    "type": "multipleChoice",
                    "properties": {
                        "label": "What are your occupations/skills/interests?",
                        "htmlType": "checkbox",
                        "conditions": [],
                        "extId": "skills",
                        "optionsEndpoint": "/members/skills/",
                        "options": [],
                        "values": []
                    },
                    "id": "NaUnduxZaNGg",
                    "children": []
                },
                {
                    "type": "multipleChoice",
                    "properties": {
                        "label": "What are your occupations/skills/interests?2",
                        "htmlType": "checkbox",
                        "conditions": [],
                        "extId": "skills",
                        "options": [
                            {
                                "id": "1",
                                "label": "test1"
                            }
                        ]
                    },
                    "id": "NaUnduxZaNGg",
                    "children": []
                },
```

2023-02-07 11:31 UTC, nanu-c commented
Depends on https://github.com/MILA-Wien/collectivo/pull/69

2023-02-08 10:41 UTC, JoelForamitti requested changes
Trying it out locally, i receive the following error: `Uncaught (in promise) TypeError: props.element.properties.options is undefined`

2023-02-14 11:33 UTC, JoelForamitti requested changes
One issue: If I select two fields, the submitted fields will not be the same.

2023-02-20 07:24 UTC, JoelForamitti approved these changes

2023-02-20 07:24 UTC, merged