Add Pagination
MILA-Wien/collectivo-ux pull request #60
Opened 2023-02-20 14:28 UTC by nanu-c

Add pagination support for data-tables. @JoelForamitti this doesn't include the filter because we have the filter disabled for most of the fields.

2023-02-21 07:58 UTC, JoelForamitti commented
> Add pagination support for data-tables. @JoelForamitti this doesn't include the filter because we have the filter disabled for most of the fields.

@nanu-c can you try with this branch: https://github.com/MILA-Wien/collectivo/pull/76

2023-03-09 15:05 UTC, JoelForamitti requested changes
Some filters send the wrong request path with icontains instead of the actually chosen filter. E.g.: The full request path looks e.g. like this: `/api/members/tags/?offset=0&limit=50&search=&id__icontains=true`

I found this problem for the following three filters:
- equals should be `=`
- in list should be `__in=` 
- is empty should be `__isnull=`

2023-03-09 15:10 UTC, JoelForamitti commented
The e2e test fails because there are not enough members to test pagination. Please test tags instead, where the latest version of https://github.com/MILA-Wien/collectivo/pull/76 comes with over 100 test tags.

2023-03-09 20:16 UTC, nanu-c commented
> Some filters send the wrong request path with icontains instead of the actually chosen filter. E.g.: The full request path looks e.g. like this: `/api/members/tags/?offset=0&limit=50&search=&id__icontains=true`
> 
> I found this problem for the following three filters:
> 
>     * equals should be `id=`
> 
>     * in list should be `id__in=`
> 
>     * is empty should be `id__isnull=`

This is resolved now.

2023-03-16 09:28 UTC, nanu-c commented
The problem here is, that even `/api/members/summary/?offset=0&limit=50&tags=1` doesn't work.

2023-03-16 09:53 UTC, nanu-c commented
Okey filters are broken on all manyToMany fields, for example this `http://collectivo.local:8000/api/members/summary/?offset=0&limit=50&groups_interested__icontains=1`

2023-03-16 10:12 UTC, JoelForamitti commented
> Okey filters are broken on all manyToMany fields, for example this `http://collectivo.local:8000/api/members/summary/?offset=0&limit=50&groups_interested__icontains=1`

Can you check if it works with this new branch? https://github.com/MILA-Wien/collectivo/pull/82

However, note that in your example there is still a syntax mistake, it should not be `groups_interested__icontains=1` but only `groups_interested=1`. Contains can only be used for strings, I think.

2023-03-16 10:45 UTC, nanu-c commented
I have disabled the contains filter as it was also changed in the backend now -> https://github.com/MILA-Wien/collectivo/pull/82/files#diff-77542745d5ea7bb012c7c9f62c6452ab89169717c3f82b0e683a331d2eed4221R21

2023-03-16 11:25 UTC, JoelForamitti requested changes
Two more issues:

- The filter for single choice does not work any more (e.g. status in members). When I try to apply it, no request is send to the backend.
- The clear filters button does not work.

2023-03-16 11:46 UTC, nanu-c commented on src/components/datatable/ObjectTable.vue
> +                class="p-column-filter fitler-1"
I have removed this.

2023-03-16 11:47 UTC, nanu-c commented
> Two more issues:
> 
>     * The filter for single choice does not work any more (e.g. status in members). When I try to apply it, no request is send to the backend.
-> solved
> 
>     * The clear filters button does not work.

The clear buttons have been removed, we need another solution for them. It can be done now by reloading the page

2023-03-16 15:12 UTC, JoelForamitti approved these changes

2023-03-16 15:12 UTC, merged