Fix iframe and add layouts
MILA-Wien/collectivo-ux pull request #80
Opened 2023-05-02 09:50 UTC by nanu-c

This depends on https://github.com/MILA-Wien/collectivo/pull/113
It introduces a layout based system in the router, has a fall back and enables to use the full space for iframes.

2023-05-02 09:51 UTC, nanu-c commented
![grafik](https://user-images.githubusercontent.com/404058/235635296-00824a7d-f0f8-4d8d-a8ca-68292f4c2604.png)

2023-05-08 06:23 UTC, JoelForamitti requested changes
Looks great!

2023-05-08 06:23 UTC, JoelForamitti commented on src/components/SidebarMenuItem.vue
> +      <span class="pt-1 w-full">{{ item.target }}{{ item.label }}</span>
I think {{ item.target }} should not be here, right?

![image](https://user-images.githubusercontent.com/57440945/236749207-a7d7d345-0629-47ec-bba8-105667691954.png)

2023-05-08 06:23 UTC, JoelForamitti commented on src/components/SidebarMenuItem.vue
> +      <span class="pt-1 w-full">iframe{{ item.label }}</span>
Same here

2023-05-26 12:05 UTC, JoelForamitti commented
Integrated into https://github.com/MILA-Wien/collectivo-ux/pull/85

2023-05-26 12:05 UTC, closed without merging